### ISSUE TITLE
Add roadmap

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#22]
What still needs to be done?

**Comment by scolby33** [comment]
In no particular order:

- [ ] tests
- [ ] fix all TODOs/FIXMEs
- [ ] More error-checking in the Flask part of the application--return reasonable errors instead of 500 Server Erroring all the time
- [ ] Sane Flask configuration (@cthoyt)
- [ ] Add About page (or section on the home page?), add Acknowledgements for Censys data, maybe Censys logo (an all white version in the green background color somewhere?)
- [ ] Obviously we need to say somehwere "Made with {heart emoji} in {wherever}"
- [ ] "Made with {broken heart emoji} far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun. Orbiting this at a distance of roughly ninety-two million miles is an utterly insignificant little blue green planet whose ape-descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea."
- [ ] Privacy policy for info on server logs (GDPR)
- [ ] Page footer with copyright, links to our pages, link to github, etc.
- [ ] Add legend for the symbols in the table
- [ ] Configure Nginx for cache times/cache busting of static assets (and maybe ~1 min or so cache in nginx for the home page so it doesn't have to call Python all the time)
- [ ] Pre-gzip (zopfli) and pre-brotli versions of static files for Nginx
- [ ] Fix docker-compose/dockerfiles so the database gets persisted
- [ ] remove anywhere it says "OCSP Dashboard" the name is OCSPdash and it is a dashboard for OCSP, but it's not an OCSP Dashboard (just for "brand" consistency)
- [ ] Make sure incomplete DB updates from Censys aren't partially committed so the manifest.jsonl endpoint isn't inconsistent
- [ ] Switch to only Python 3.7 and update all references to 3.6 (Pipfile, docs, readme, etc.)
- [ ] there was one other thing that seemed important but I can't remember it

Possibly do:

- [ ] Move OCSPscrape to a separate package
- [ ] Use UWSGI with good tuning

Later, after release:

- [ ] Switch from Censys REST API to BigQuery (make sure we stay under monthly BigQuery free tier--store number of requests in the DB or something?)

**Comment by scolby33** [comment]
@cthoyt if you want to open issues for all these, that might be a fun idea.

**Comment by scolby33** [comment]
"Made with 💔 on an utterly insignificant little blue green planet whose ape-descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea orbiting at a distance of roughly ninety-two million miles from a small unregarded yellow sun far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy." with apologies to Douglas Adams

**Comment by cthoyt** [comment]
I still don't like the idea of having OCSPscrape in a different repo because then it's hard (if not impossible) to stay consistent (I know from experience with PyBEL/PyBEL Tools/PyBEL Web)

**Comment by scolby33** [comment]
Understood, let's leave it where it is for now.

Maybe gate the webapp behind a setuptools feature? I'm sorta worried (although probably uselessly...) about the install footprint for someone who just needs OCSPscrape.

**Comment by cthoyt** [comment]
yeah I worry about this too

but also

we use like 60% of the cropland in the USA to make ethanol, and disk space is basically free. Should we even care about install footprint (i've also done hacky things to keep requirements lean)

**Comment by scolby33** [comment]
Interestingly in this case it shouldn't be *too* hard to stay in sync since we only need to use the REST api.

I'm happy leaving this until it's a problem. @ FutureCharlie & FutureScott
